name: Tests and Linters 🧪

on: [ push, pull_request ]

jobs:
  tests-and-linters:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest]

    steps:
    - name: Checkout marl_eval
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install python dependencies
      run: pip install .[dev]
    - name: List python packages 📦
      run: pip list
    - name: Run linters 🖌️
      run: pre-commit run --all-files --verbose
    - name: Run tests 🧪
      run: pytest -n 2 tests
